[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my-agent"
version = "0.3.0.dev0"
description = "A Basic Bot agent"
requires-python = ">=3.14"
dependencies = [
    "basic-bot[local] @ git+https://github.com/CablepunkPress/basic-bot.git@v0.7.0",
    "basic-ui @ git+https://github.com/CablepunkPress/basic-ui.git@v0.2.0",
]

[tool.setuptools]
packages = []
